# Generated by Django 5.1 on 2025-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabajet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemen1',
            fields=[
                ('e1id', models.AutoField(primary_key=True, serialize=False)),
                ('e1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('list_lokasi', models.CharField(max_length=255)),
            ],
        ),
    ]
