# Generated by Django 5.2.3 on 2025-08-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabajet', '0002_elemen1_lokasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemen5',
            fields=[
                ('e5id', models.AutoField(primary_key=True, serialize=False)),
                ('e5', models.TextField()),
            ],
        ),
    ]
