# Generated by Django 5.1 on 2025-08-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabajet', '0003_elemen2_elemen3_elemen4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('asetid', models.AutoField(primary_key=True, serialize=False)),
                ('list_aset', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Elemen5',
            fields=[
                ('e5id', models.AutoField(primary_key=True, serialize=False)),
                ('e5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen6',
            fields=[
                ('e6id', models.AutoField(primary_key=True, serialize=False)),
                ('e6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen7',
            fields=[
                ('e7id', models.AutoField(primary_key=True, serialize=False)),
                ('e7', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen8',
            fields=[
                ('e8id', models.AutoField(primary_key=True, serialize=False)),
                ('e8', models.TextField()),
            ],
        ),
    ]
