# Generated by Django 5.2.3 on 2025-08-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabajet', '0003_elemen5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemen2',
            fields=[
                ('e2id', models.AutoField(primary_key=True, serialize=False)),
                ('e2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen3',
            fields=[
                ('e3id', models.AutoField(primary_key=True, serialize=False)),
                ('e3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen4',
            fields=[
                ('e4id', models.AutoField(primary_key=True, serialize=False)),
                ('e4', models.TextField()),
            ],
        ),
    ]
