# Generated by Django 5.2.3 on 2025-08-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabajet', '0004_elemen2_elemen3_elemen4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemen6',
            fields=[
                ('e6id', models.AutoField(primary_key=True, serialize=False)),
                ('e6', models.TextField()),
            ],
        ),
    ]
