# Generated by Django 5.2.3 on 2025-08-06 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabajet', '0005_elemen6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemen7',
            fields=[
                ('e7id', models.AutoField(primary_key=True, serialize=False)),
                ('e7', models.TextField()),
            ],
        ),
    ]
