# Generated by Django 5.2.3 on 2025-08-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabajet', '0006_elemen7'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemen8',
            fields=[
                ('e8id', models.AutoField(primary_key=True, serialize=False)),
                ('e8', models.TextField()),
            ],
        ),
    ]
