# Generated by Django 5.2.3 on 2025-08-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideabajet', '0007_elemen8'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('asetid', models.AutoField(primary_key=True, serialize=False)),
                ('list_aset', models.CharField(max_length=255)),
            ],
        ),
    ]
